In [7]:
import pandas as pd
info = {
    "Name":["kunal","Anil","mahesh"],
    "age":[19,20,31],
    "CGPA":[9,9.1,9.5]
}

df = pd.DataFrame(info)
print (df)
print  (df.index)
print (df.columns)

     Name  age  CGPA
0   kunal   19   9.0
1    Anil   20   9.1
2  mahesh   31   9.5
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'age', 'CGPA'], dtype='str')

In [10]:
df

     Name  age  CGPA
0   kunal   19   9.0
1    Anil   20   9.1
2  mahesh   31   9.5

In [14]:
import pandas as pd
df = pd.DataFrame([["kunal",20],["anil",21],["mahesh",31]], columns = ["name","age"])
print (df)

     name  age
0   kunal   20
1    anil   21
2  mahesh   31

In [15]:
df

     name  age
0   kunal   20
1    anil   21
2  mahesh   31

In [18]:
import numpy as np 
import pandas as pd

data = np.array([[1,2,3],[1,2,3]])
df = pd.DataFrame(data,columns=["a","b","c"])
print(df)

   a  b  c
0  1  2  3
1  1  2  3