In [2]:
import pandas as pd

df = pd.read_csv("data.csv")  #for json fromat it will be pd.read_json
print (df)

    Student_ID    Name  Age  Gender    City  Study_Hours  Attendance  \
0          101   Kunal   20    Male    Pune          4.5          92
1          102   Rahul   21    Male  Mumbai          3.0          85
2          103   Priya   20  Female  Nashik          5.0          95
3          104    Aman   22    Male    Pune          2.0          72
4          105    Neha   20  Female  Mumbai          4.0          88
5          106  Aditya   21    Male  Nagpur          1.5          68
6          107   Sneha   20  Female    Pune          5.5          96
7          108   Rohan   22    Male  Nashik          2.5          75
8          109    Isha   21  Female  Mumbai          3.5          90
9          110   Vivek   20    Male    Pune          4.0          86
10         111  Anjali   21  Female  Nagpur          2.0          70
11         112   Akash   22    Male  Mumbai          3.0          80
12         113   Meera   20  Female    Pune          6.0          98
13         114   Sahil   21    Male  Nashik          2.5          78
14         115    Riya   20  Female  Mumbai          4.5          93
15         116      Om   22    Male  Nagpur          1.0          65
16         117   Pooja   21  Female    Pune          3.5          87
17         118   Harsh   20    Male  Mumbai          2.0          74
18         119  Simran   21  Female  Nashik          5.0          94
19         120    Yash   22    Male    Pune          3.0          82

    Math_Score  Python_Score  DSA_Score  Projects Placement_Status
0           88            91         85         3           Placed
1           76            82         78         2       Not Placed
2           91            94         89         4           Placed
3           65            70         61         1       Not Placed
4           84            87         80         3           Placed
5           59            64         55         0       Not Placed
6           94            96         92         5           Placed
7           70            73         68         1       Not Placed
8           82            89         84         3           Placed
9           79            85         81         2           Placed
10          63            68         60         1       Not Placed
11          72            77         74         2       Not Placed
12          96            97         95         6           Placed
13          68            71         65         1       Not Placed
14          89            92         88         4           Placed
15          55            60         52         0       Not Placed
16          80            84         79         2           Placed
17          62            69         64         1       Not Placed
18          90            93         91         4           Placed
19          75            79         76         2       Not Placed

In [3]:
df

,Student_ID,Name,Age,Gender,City,Study_Hours,Attendance,Math_Score,Python_Score,DSA_Score,Projects,Placement_Status
0,101,Kunal,20,Male,Pune,4.5,92,88,91,85,3,Placed
1,102,Rahul,21,Male,Mumbai,3.0,85,76,82,78,2,Not Placed
2,103,Priya,20,Female,Nashik,5.0,95,91,94,89,4,Placed
3,104,Aman,22,Male,Pune,2.0,72,65,70,61,1,Not Placed
4,105,Neha,20,Female,Mumbai,4.0,88,84,87,80,3,Placed
5,106,Aditya,21,Male,Nagpur,1.5,68,59,64,55,0,Not Placed
6,107,Sneha,20,Female,Pune,5.5,96,94,96,92,5,Placed
7,108,Rohan,22,Male,Nashik,2.5,75,70,73,68,1,Not Placed
8,109,Isha,21,Female,Mumbai,3.5,90,82,89,84,3,Placed
9,110,Vivek,20,Male,Pune,4.0,86,79,85,81,2,Placed
10,111,Anjali,21,Female,Nagpur,2.0,70,63,68,60,1,Not Placed
11,112,Akash,22,Male,Mumbai,3.0,80,72,77,74,2,Not Placed
12,113,Meera,20,Female,Pune,6.0,98,96,97,95,6,Placed
13,114,Sahil,21,Male,Nashik,2.5,78,68,71,65,1,Not Placed
14,115,Riya,20,Female,Mumbai,4.5,93,89,92,88,4,Placed
15,116,Om,22,Male,Nagpur,1.0,65,55,60,52,0,Not Placed
16,117,Pooja,21,Female,Pune,3.5,87,80,84,79,2,Placed
17,118,Harsh,20,Male,Mumbai,2.0,74,62,69,64,1,Not Placed
18,119,Simran,21,Female,Nashik,5.0,94,90,93,91,4,Placed
19,120,Yash,22,Male,Pune,3.0,82,75,79,76,2,Not Placed

In [4]:
# going to perform the  operation on data which is called DataFrame method
df.head() #it will give the first 5 valus

,Student_ID,Name,Age,Gender,City,Study_Hours,Attendance,Math_Score,Python_Score,DSA_Score,Projects,Placement_Status
0,101,Kunal,20,Male,Pune,4.5,92,88,91,85,3,Placed
1,102,Rahul,21,Male,Mumbai,3.0,85,76,82,78,2,Not Placed
2,103,Priya,20,Female,Nashik,5.0,95,91,94,89,4,Placed
3,104,Aman,22,Male,Pune,2.0,72,65,70,61,1,Not Placed
4,105,Neha,20,Female,Mumbai,4.0,88,84,87,80,3,Placed

In [5]:
df.tail()   # it will give the last 5 value and if we pass the value inside can be printed in op
# df.tail(1)

,Student_ID,Name,Age,Gender,City,Study_Hours,Attendance,Math_Score,Python_Score,DSA_Score,Projects,Placement_Status
15,116,Om,22,Male,Nagpur,1.0,65,55,60,52,0,Not Placed
16,117,Pooja,21,Female,Pune,3.5,87,80,84,79,2,Placed
17,118,Harsh,20,Male,Mumbai,2.0,74,62,69,64,1,Not Placed
18,119,Simran,21,Female,Nashik,5.0,94,90,93,91,4,Placed
19,120,Yash,22,Male,Pune,3.0,82,75,79,76,2,Not Placed

In [6]:
df.sample()  #any randome  sample  is given

,Student_ID,Name,Age,Gender,City,Study_Hours,Attendance,Math_Score,Python_Score,DSA_Score,Projects,Placement_Status
14,115,Riya,20,Female,Mumbai,4.5,93,89,92,88,4,Placed

In [7]:
df.info()  # give overall report of the data

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        20 non-null     int64
 1   Name              20 non-null     str
 2   Age               20 non-null     int64
 3   Gender            20 non-null     str
 4   City              20 non-null     str
 5   Study_Hours       20 non-null     float64
 6   Attendance        20 non-null     int64
 7   Math_Score        20 non-null     int64
 8   Python_Score      20 non-null     int64
 9   DSA_Score         20 non-null     int64
 10  Projects          20 non-null     int64
 11  Placement_Status  20 non-null     str
dtypes: float64(1), int64(7), str(4)
memory usage: 2.5 KB

In [8]:
df.shape   #it gives tuple size 20rows and 12 columns

(20, 12)

In [9]:
df.columns  #gives the name of each columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'City', 'Study_Hours',
       'Attendance', 'Math_Score', 'Python_Score', 'DSA_Score', 'Projects',
       'Placement_Status'],
      dtype='str')

In [10]:
df.describe()

,Student_ID,Age,Study_Hours,Attendance,Math_Score,Python_Score,DSA_Score,Projects
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,110.50000,20.850000,3.400000,83.400000,76.900000,81.050000,75.850000,2.350000
std,5.91608,0.812728,1.391705,10.153558,12.353989,11.445408,12.946347,1.631112
min,101.00000,20.000000,1.000000,65.000000,55.000000,60.000000,52.000000,0.000000
25%,105.75000,20.000000,2.375000,74.750000,67.250000,70.750000,64.750000,1.000000
50%,110.50000,21.000000,3.250000,85.500000,77.500000,83.000000,78.500000,2.000000
75%,115.25000,21.250000,4.500000,92.250000,88.250000,91.250000,85.750000,3.250000
max,120.00000,22.000000,6.000000,98.000000,96.000000,97.000000,95.000000,6.000000

In [11]:
# give data which is unique which is not repeted
df.nunique()

Student_ID          20
Name                20
Age                  3
Gender               2
City                 4
Study_Hours         11
Attendance          20
Math_Score          20
Python_Score        20
DSA_Score           20
Projects             7
Placement_Status     2
dtype: int64