In [4]:
import pandas as pd

df = pd.read_csv("raw_data.csv")

In [5]:
df.isnull()  #we can also use isna() same meaning 

df.isnull().sum()     #returns the sum of all NaN

df.dropna()

df.dropna(axis = 1)
# df.fillna(0.0)

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [6]:
# cleaning the data 
# age_mean = df["age"].mean()

clean_data = df.copy()
age_mean = clean_data["age"].mean()
clean_data["age"] = clean_data["age"].fillna(age_mean)

clean_data

    id          name    age country   gender
0    1      John Doe  29.00     USA     Male
1    1      John Doe  29.00     USA     Male
2    2    Jane Smith  32.75  Canada   Female
3    3          Alex  32.75     USA  Unknown
4    4  Maria Garcia  34.00   Spain   Female
5    5        Li Wei  27.00   China     Male
6    6    Ahmed Khan  45.00   India   Female
7    7           NaN  38.00     NaN     Male
8    8    Rachel Lee  29.00     USA   Female
9    9   Carlos Ruiz  32.75  Mexico      NaN
10  10   Emily Davis  31.00     USA      NaN

In [12]:
df.ffill()  #fills the empty nan with its about row value ex 1,2 (nan)=2
df.bfill()   #visa versa of forward fill and this is bacword fill

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
1    1      John Doe  29.0     USA     Male
2    2    Jane Smith  34.0  Canada   Female
3    3          Alex  34.0     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6    Ahmed Khan  45.0   India   Female
7    7    Rachel Lee  38.0     USA     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz  31.0  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN

In [23]:
# handale the duplicate value
df.duplicated()
# df["country"].duplicated()
df[["country","gender"]].duplicated()

# df.drop_duplicates(inplace=True)

In [25]:
df

    id          name   age country   gender
0    1      John Doe  29.0     USA     Male
2    2    Jane Smith   NaN  Canada   Female
3    3          Alex   NaN     USA  Unknown
4    4  Maria Garcia  34.0   Spain   Female
5    5        Li Wei  27.0   China     Male
6    6    Ahmed Khan  45.0   India   Female
7    7           NaN  38.0     NaN     Male
8    8    Rachel Lee  29.0     USA   Female
9    9   Carlos Ruiz   NaN  Mexico      NaN
10  10   Emily Davis  31.0     USA      NaN